#!/usr/bin/env bash
# Test doubles are invoked indirectly by sourced helpers.
# shellcheck disable=SC2317
set -Eeuo pipefail

ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
TEST_PYTHON_BIN="$(command -v python3 || command -v python)"
# shellcheck source=../recover.sh
source "${ROOT}/recover.sh"

# install.sh intentionally replaces PATH for root safety. Keep the exact test
# interpreter selected before sourcing so these tests also run under Git Bash.
python3() { "$TEST_PYTHON_BIN" "$@"; }

expect_success() {
    "$@" || {
        printf 'expected success: %q\n' "$*" >&2
        exit 1
    }
}

expect_failure() {
    if "$@"; then
        printf 'expected failure: %q\n' "$*" >&2
        exit 1
    fi
}

expect_exit_code() {
    local expected="$1"
    shift
    local actual=0
    set +e
    "$@"
    actual=$?
    set -e
    if (( actual != expected )); then
        printf 'expected exit %s, got %s: %q\n' "$expected" "$actual" "$*" >&2
        exit 1
    fi
}

expect_success validate_ipv4 203.0.113.10
expect_success validate_ipv4 1.1.1.1
expect_failure validate_ipv4 999.1.1.1
expect_failure validate_ipv4 127.0.0
expect_failure validate_ipv4 0.0.0.0
expect_failure validate_ipv4 '1.2.3.4 extra'

expect_success validate_port 1
expect_success validate_port 10443
expect_success validate_port 65535
expect_failure validate_port 0
expect_failure validate_port 65536
expect_failure validate_port abc

iptables_snapshot_a=$'# Generated by iptables-save v1.8.10\n*filter\n:INPUT ACCEPT [10:900]\n:FORWARD DROP [3:240]\n-A INPUT -p tcp --dport 2222 -j ACCEPT\nCOMMIT\n# Completed on test host'
iptables_snapshot_b=$'# Generated by iptables-save v1.8.10\n*filter\n:INPUT ACCEPT [99999:123456789]\n:FORWARD DROP [77:8800]\n-A INPUT -p tcp --dport 2222 -j ACCEPT\nCOMMIT\n# Completed on another host'
iptables_policy_change=$'*filter\n:INPUT DROP [99999:123456789]\n:FORWARD DROP [77:8800]\n-A INPUT -p tcp --dport 2222 -j ACCEPT\nCOMMIT'
normalized_a="$(normalize_iptables_save <<<"$iptables_snapshot_a")"
normalized_b="$(normalize_iptables_save <<<"$iptables_snapshot_b")"
normalized_policy_change="$(normalize_iptables_save <<<"$iptables_policy_change")"
[[ "$normalized_a" == "$normalized_b" ]]
[[ "$normalized_a" != "$normalized_policy_change" ]]

nft_before_restore=$'# Warning: table ip nat is managed by iptables-nft\ntable ip nat {\n\tchain DOCKER {\n\t}\n\tchain PREROUTING {\n\t\ttype nat hook prerouting priority dstnat; policy accept;\n\t}\n}\ntable inet operator-policy {\n\tchain input {\n\t\ttype filter hook input priority 10; policy accept;\n\t}\n}\n# Warning: table ip filter is managed by iptables-nft\ntable ip filter {\n\tchain INPUT {\n\t\ttype filter hook input priority filter; policy accept;\n\t}\n}\ntable ip remnanode {\n\tset ingress-filter-ip {\n\t\ttype ipv4_addr\n\t}\n}\ntable ip6 remnanode6 {\n\tchain output {\n\t\ttype filter hook output priority -10; policy accept;\n\t}\n}\ntable ip remnanode-shadow {\n\tchain input {\n\t}\n}'
nft_after_restore=$'# Warning: table ip filter is managed by iptables-nft\ntable ip filter {\n\tchain INPUT {\n\t\ttype filter hook input priority filter; policy accept;\n\t}\n}\n# Warning: table ip nat is managed by iptables-nft\ntable ip nat {\n\tchain PREROUTING {\n\t\ttype nat hook prerouting priority dstnat; policy accept;\n\t}\n\tchain INPUT {\n\t\ttype nat hook input priority srcnat; policy accept;\n\t}\n\tchain POSTROUTING {\n\t\ttype nat hook postrouting priority srcnat; policy accept;\n\t}\n\tchain DOCKER {\n\t}\n}\ntable inet operator-policy {\n\tchain input {\n\t\ttype filter hook input priority 10; policy accept;\n\t}\n}\ntable ip remnanode-shadow {\n\tchain input {\n\t}\n}'
nft_policy_before="$(filter_host_policy_nft_tables 1 1 <<<"$nft_before_restore")"
nft_policy_after="$(filter_host_policy_nft_tables 1 1 <<<"$nft_after_restore")"
[[ "$nft_policy_before" == "$nft_policy_after" ]]
[[ "$nft_policy_before" == *'table inet operator-policy {'* ]]
[[ "$nft_policy_before" == *'table ip remnanode-shadow {'* ]]
[[ "$nft_policy_before" == *'table ip filter {'* ]]
[[ "$nft_policy_before" == *'table ip nat {'* ]]
[[ "$nft_policy_before" != *'table ip remnanode {'* ]]
[[ "$nft_policy_before" != *'table ip6 remnanode6 {'* ]]
[[ "$(filter_host_policy_nft_tables 0 0 <<<"$nft_before_restore")" == *'table ip filter {'* ]]
expect_failure filter_host_policy_nft_tables 1 1 <<<'table ip remnanode {'
nft_priority_collision="${nft_before_restore/priority 10/priority 0}"
expect_failure filter_host_policy_nft_tables 1 1 <<<"$nft_priority_collision"
legacy_filtered="$(filter_managed_node_nft_tables_legacy <<<"$nft_before_restore")"
[[ "$legacy_filtered" == *'# Warning: table ip nat is managed by iptables-nft'* ]]
[[ "$legacy_filtered" == *'table ip filter {'* ]]
[[ "$legacy_filtered" != *'table ip remnanode {'* ]]
expect_failure filter_managed_node_nft_tables_legacy <<<'table ip remnanode {'

nft_native_policy_change="${nft_before_restore/type filter hook input priority 10; policy accept/type filter hook input priority 10; policy drop}"
compat_native_rule=$'type filter hook input priority filter; policy accept;\n\t\tip saddr 198.51.100.20 drop;'
nft_compat_native_change="${nft_before_restore/type filter hook input priority filter; policy accept;/$compat_native_rule}"

iptables() { printf 'iptables v1.8.10 (nf_tables)\n'; }
ip6tables() { printf 'ip6tables v1.8.10 (nf_tables)\n'; }
iptables-save() { printf '%s\n' "$iptables_snapshot_a"; }
ip6tables-save() { printf '%s\n' "$iptables_snapshot_a"; }
nft() { printf '%s\n' "$nft_before_restore"; }
effective_before_restore="$(compute_effective_firewall_hash)"
nft() { printf '%s\n' "$nft_after_restore"; }
effective_after_restore="$(compute_effective_firewall_hash)"
[[ "$effective_before_restore" == "$effective_after_restore" ]]
nft() { printf '%s\n' "$nft_native_policy_change"; }
[[ "$(compute_effective_firewall_hash)" != "$effective_before_restore" ]]
nft() { printf '%s\n' "$nft_compat_native_change"; }
[[ "$(compute_effective_firewall_hash)" != "$effective_before_restore" ]]
nft() { printf '%s\n' "$nft_after_restore"; }
iptables-save() { printf '%s\n' "$iptables_policy_change"; }
[[ "$(compute_effective_firewall_hash)" != "$effective_before_restore" ]]
iptables-save() { printf '%s\n' "$iptables_snapshot_a"; }

iptables_with_ufw=$'*filter\n:INPUT ACCEPT [0:0]\n:FORWARD ACCEPT [0:0]\n:OUTPUT ACCEPT [0:0]\n:DOCKER-USER - [0:0]\n:ufw-before-input - [0:0]\n:ufw6-before-input - [0:0]\n-A INPUT -j ufw-before-input\n-A FORWARD -j DOCKER-USER\n-A ufw-before-input -s 1.2.3.4 -j ACCEPT\n-A ufw6-before-input -j ACCEPT\nCOMMIT'
iptables_without_ufw="$(filter_inactive_ufw_iptables_save <<<"$iptables_with_ufw")"
[[ "$iptables_without_ufw" == *':DOCKER-USER - [0:0]'* ]]
[[ "$iptables_without_ufw" == *'-A FORWARD -j DOCKER-USER'* ]]
[[ "$iptables_without_ufw" != *'ufw-before-input'* ]]
[[ "$iptables_without_ufw" != *'ufw6-before-input'* ]]

tmp="$(mktemp)"
tmp_restore="$(mktemp)"
trap 'rm -f -- "$tmp" "$tmp_restore"' EXIT

v105_pristine=$'*filter\n:INPUT ACCEPT [0:0]\n:FORWARD ACCEPT [0:0]\n:OUTPUT ACCEPT [0:0]\nCOMMIT'
v105_docker_ipv4=$'*filter\n:INPUT ACCEPT [0:0]\n:FORWARD ACCEPT [0:0]\n:OUTPUT ACCEPT [0:0]\n:DOCKER - [0:0]\n:DOCKER-BRIDGE - [0:0]\n:DOCKER-CT - [0:0]\n:DOCKER-FORWARD - [0:0]\n:DOCKER-INTERNAL - [0:0]\n:DOCKER-USER - [0:0]\n-A FORWARD -j DOCKER-USER\n-A FORWARD -j DOCKER-FORWARD\n-A DOCKER ! -i docker0 -o docker0 -j DROP\n-A DOCKER-BRIDGE -o docker0 -j DOCKER\n-A DOCKER-CT -o docker0 -m conntrack --ctstate RELATED,ESTABLISHED -j ACCEPT\n-A DOCKER-FORWARD -j DOCKER-CT\n-A DOCKER-FORWARD -j DOCKER-INTERNAL\n-A DOCKER-FORWARD -j DOCKER-BRIDGE\n-A DOCKER-FORWARD -i docker0 -j ACCEPT\nCOMMIT\n*nat\n:PREROUTING ACCEPT [0:0]\n:INPUT ACCEPT [0:0]\n:OUTPUT ACCEPT [0:0]\n:POSTROUTING ACCEPT [0:0]\n:DOCKER - [0:0]\n-A PREROUTING -m addrtype --dst-type LOCAL -j DOCKER\n-A OUTPUT ! -d 127.0.0.0/8 -m addrtype --dst-type LOCAL -j DOCKER\n-A POSTROUTING -s 172.17.0.0/16 ! -o docker0 -j MASQUERADE\nCOMMIT'
v105_docker_ipv6=$'# Generated by ip6tables-save v1.8.10 (nf_tables)\n*filter\n:INPUT ACCEPT [2107:311733]\n:FORWARD ACCEPT [0:0]\n:OUTPUT ACCEPT [418:28584]\n:DOCKER - [0:0]\n:DOCKER-BRIDGE - [0:0]\n:DOCKER-CT - [0:0]\n:DOCKER-FORWARD - [0:0]\n:DOCKER-INTERNAL - [0:0]\n:DOCKER-USER - [0:0]\n-A FORWARD -j DOCKER-USER\n-A FORWARD -j DOCKER-FORWARD\n-A DOCKER-FORWARD -j DOCKER-CT\n-A DOCKER-FORWARD -j DOCKER-INTERNAL\n-A DOCKER-FORWARD -j DOCKER-BRIDGE\nCOMMIT\n# Completed IPv6 filter\n*nat\n:PREROUTING ACCEPT [0:0]\n:INPUT ACCEPT [0:0]\n:OUTPUT ACCEPT [0:0]\n:POSTROUTING ACCEPT [0:0]\n:DOCKER - [0:0]\n-A PREROUTING -m addrtype --dst-type LOCAL -j DOCKER\n-A OUTPUT ! -d ::1/128 -m addrtype --dst-type LOCAL -j DOCKER\nCOMMIT\n# Completed IPv6 nat'
printf '%s\n' "$v105_pristine" >"$tmp_restore"
expect_success assert_v105_docker_only_restore_image "$tmp_restore" none
expect_success assert_v105_docker_only_restore_image "$tmp_restore" ipv4
expect_success assert_v105_docker_only_restore_image "$tmp_restore" ipv6
printf '%s\n' "$v105_docker_ipv4" >"$tmp_restore"
expect_success assert_v105_docker_only_restore_image "$tmp_restore" ipv4
expect_failure assert_v105_docker_only_restore_image "$tmp_restore" none
expect_failure assert_v105_docker_only_restore_image "$tmp_restore" ipv6
printf '%s\n' "${v105_docker_ipv4/-A FORWARD -j DOCKER-USER$'\n'-A FORWARD -j DOCKER-FORWARD/-A FORWARD -j DOCKER-FORWARD$'\n'-A FORWARD -j DOCKER-USER}" >"$tmp_restore"
expect_failure assert_v105_docker_only_restore_image "$tmp_restore" ipv4
printf '%s\n' "${v105_docker_ipv4/-A DOCKER ! -i docker0 -o docker0 -j DROP/-A DOCKER ! -i docker0 -o docker0 -j ACCEPT}" >"$tmp_restore"
expect_failure assert_v105_docker_only_restore_image "$tmp_restore" ipv4
printf '%s\n' "${v105_docker_ipv4/:FORWARD ACCEPT/:FORWARD DROP}" >"$tmp_restore"
expect_success assert_v105_docker_only_restore_image "$tmp_restore" ipv4
printf '%s\n' "$v105_docker_ipv6" >"$tmp_restore"
expect_success assert_v105_docker_only_restore_image "$tmp_restore" ipv6
expect_failure assert_v105_docker_only_restore_image "$tmp_restore" none
expect_failure assert_v105_docker_only_restore_image "$tmp_restore" ipv4
printf '%s\n' "${v105_docker_ipv6/-A DOCKER-FORWARD -j DOCKER-CT$'\n'-A DOCKER-FORWARD -j DOCKER-INTERNAL/-A DOCKER-FORWARD -j DOCKER-INTERNAL$'\n'-A DOCKER-FORWARD -j DOCKER-CT}" >"$tmp_restore"
expect_failure assert_v105_docker_only_restore_image "$tmp_restore" ipv6
printf '%s\n' "${v105_docker_ipv6/-A OUTPUT ! -d ::1\/128 -m addrtype --dst-type LOCAL -j DOCKER/-A OUTPUT ! -d ::\/0 -m addrtype --dst-type LOCAL -j DOCKER}" >"$tmp_restore"
expect_failure assert_v105_docker_only_restore_image "$tmp_restore" ipv6
printf '%s\n' "${v105_docker_ipv6/-A FORWARD -j DOCKER-USER/-A FORWARD -j DOCKER-USER$'\n'-A DOCKER-USER -j ACCEPT}" >"$tmp_restore"
expect_failure assert_v105_docker_only_restore_image "$tmp_restore" ipv6
printf '%s\n' "$v105_pristine" >"$tmp_restore"
expect_failure assert_v105_docker_only_restore_image "$tmp_restore" unexpected

v105_ufw_drop=$'*filter\n:INPUT DROP [10:20]\n:FORWARD DROP [30:40]\n:OUTPUT DROP [50:60]\nCOMMIT'
v105_normalized="$(normalize_v105_builtin_policies <<<"$v105_ufw_drop")"
[[ "$v105_normalized" == *':INPUT ACCEPT [10:20]'* ]]
[[ "$v105_normalized" == *':OUTPUT ACCEPT [50:60]'* ]]
[[ "$v105_normalized" == *':FORWARD DROP [30:40]'* ]]

runtime_inventory_failure_probe() (
    docker_inventory_snapshot() { return 1; }
    assert_pristine_secondary_legacy_backends() { return 0; }
    assert_recovery_runtime_provable
)
expect_failure runtime_inventory_failure_probe

stopped_remnanode_probe() (
    local mock_inventory="$1"
    local mock_running="$2"
    docker_inventory_snapshot() { printf '%s\n' "$mock_inventory"; }
    docker() {
        [[ "$1" == 'inspect' ]] || return 1
        if [[ "$2" == 'remnanode' ]]; then
            return 0
        fi
        [[ "$2" == '--format' && "$4" == 'remnanode' ]] || return 1
        case "$3" in
            *State.Running*) printf '%s\n' "$mock_running" ;;
            *Config.Image*) printf '%s\n' "$NODE_IMAGE" ;;
            *project.working_dir*) printf '%s\n' "$INSTALL_DIR" ;;
            *) return 1 ;;
        esac
    }
    assert_verified_stopped_remnanode_only
)
stopped_inventory=$'abc123\tremnanode\tmanaged-image\texited'
foreign_inventory="${stopped_inventory}"$'\ndef456\tforeign\tforeign-image\texited'
expect_success stopped_remnanode_probe "$stopped_inventory" false
expect_failure stopped_remnanode_probe "$foreign_inventory" false
expect_failure stopped_remnanode_probe "$stopped_inventory" true

initial_stopped_runtime_probe() (
    RECOVERY_INITIAL_CONTAINER_PRESENT=1
    RECOVERY_INITIAL_CONTAINER_RUNNING=0
    assert_verified_stopped_remnanode_only() { return 0; }
    assert_pristine_secondary_legacy_backends() { return 0; }
    assert_initial_recovery_runtime_provable
)
expect_success initial_stopped_runtime_probe

native_snapshot_failure_probe() (
    iptables() { printf 'iptables v1.8.10 (nf_tables)\n'; }
    ip6tables() { printf 'ip6tables v1.8.10 (nf_tables)\n'; }
    nft() { return 1; }
    compute_native_nft_policy_hash
)
expect_failure native_snapshot_failure_probe

printf 'A=one\nSECRET_KEY=abc=def==\n' >"$tmp"
[[ "$(read_setting A "$tmp")" == "one" ]]
[[ "$(read_setting SECRET_KEY "$tmp")" == "abc=def==" ]]

raw_evidence=$'### iptables-save\n*filter\nCOMMIT\n### nft stateless ruleset\n'
raw_evidence+="$nft_before_restore"
printf '%s\n' "$raw_evidence" >"$tmp_restore"
[[ "$(native_nft_policy_hash_from_raw_evidence "$tmp_restore")" == \
    "$(nft() { printf '%s\n' "$nft_before_restore"; }; compute_native_nft_policy_hash)" ]]

printf '%s\n' "$iptables_snapshot_a" >"$tmp_restore"
mock_iptables_save() { printf '%s\n' "$iptables_snapshot_b"; }
expect_success iptables_restore_image_matches_live "$tmp_restore" mock_iptables_save
mock_iptables_save() { printf '%s\n' "$iptables_policy_change"; }
expect_failure iptables_restore_image_matches_live "$tmp_restore" mock_iptables_save

PANEL_IP=''
NODE_PORT='2222'
HY2_PORT='10443'
PANEL_IP_SET=0
NODE_PORT_SET=0
HY2_PORT_SET=0
FIREWALL_MODE_SET=0
FIREWALL_MODE='ufw'
parse_args --panel-ip 203.0.113.10 --node-port 2222 --hy2-port 10443 --external-firewall
[[ "$PANEL_IP" == '203.0.113.10' && "$PANEL_IP_SET" == 1 ]]
[[ "$NODE_PORT" == '2222' && "$NODE_PORT_SET" == 1 ]]
[[ "$HY2_PORT" == '10443' && "$HY2_PORT_SET" == 1 ]]
[[ "$FIREWALL_MODE" == 'external' && "$FIREWALL_MODE_SET" == 1 ]]

safe_ufw=$'Status: active\nDefault: deny (incoming), allow (outgoing), disabled (routed)\n22/tcp  ALLOW IN  Anywhere\n2222/tcp  ALLOW IN  203.0.113.10'
exact_public=$'Status: active\nDefault: deny (incoming), allow (outgoing), disabled (routed)\n2222/tcp  ALLOW IN  Anywhere'
range_public=$'Status: active\nDefault: deny (incoming), allow (outgoing), disabled (routed)\n2000:3000/tcp  ALLOW IN  Anywhere'
all_public=$'Status: active\nDefault: deny (incoming), allow (outgoing), disabled (routed)\nAnywhere  ALLOW IN  Anywhere'
other_source=$'Status: active\nDefault: deny (incoming), allow (outgoing), disabled (routed)\n2222/tcp  ALLOW IN  198.51.100.20'
panel_denied=$'Status: active\nDefault: deny (incoming), allow (outgoing), disabled (routed)\n2222/tcp  DENY IN  203.0.113.10'
limited=$'Status: active\nDefault: deny (incoming), allow (outgoing), disabled (routed)\n2222/tcp  LIMIT IN  203.0.113.10'
udp_only=$'Status: active\nDefault: deny (incoming), allow (outgoing), disabled (routed)\n2222/udp  ALLOW IN  Anywhere\n2222/tcp  ALLOW IN  203.0.113.10'
malformed_rule=$'Status: active\n2222/tcp ALLOW IN broken-spacing'
expect_exit_code 1 find_unsafe_ufw_rule "$safe_ufw" 2222 203.0.113.10
expect_exit_code 0 find_unsafe_ufw_rule "$exact_public" 2222 203.0.113.10
expect_exit_code 0 find_unsafe_ufw_rule "$range_public" 2222 203.0.113.10
expect_exit_code 0 find_unsafe_ufw_rule "$all_public" 2222 203.0.113.10
expect_exit_code 0 find_unsafe_ufw_rule "$other_source" 2222 203.0.113.10
expect_exit_code 0 find_unsafe_ufw_rule "$panel_denied" 2222 203.0.113.10
expect_exit_code 0 find_unsafe_ufw_rule "$limited" 2222 203.0.113.10
expect_exit_code 1 find_unsafe_ufw_rule "$udp_only" 2222 203.0.113.10
expect_exit_code 2 find_unsafe_ufw_rule "$safe_ufw" invalid 203.0.113.10
expect_exit_code 2 find_unsafe_ufw_rule "$malformed_rule" 2222 203.0.113.10

python_failure_probe() {
    (
        # shellcheck disable=SC2329
        python3() { return 127; }
        find_unsafe_ufw_rule "$safe_ufw" 2222 203.0.113.10
    )
}
expect_exit_code 2 python_failure_probe

MOCK_CONTAINER_PIDS='101'
MOCK_LISTENER_LINES=''
MOCK_LISTENER_KEY='udp:10443'
container_pids() { printf '%s\n' "$MOCK_CONTAINER_PIDS"; }
listener_lines() {
    [[ "${1}:${2}" == "$MOCK_LISTENER_KEY" ]] || return 0
    printf '%s\n' "$MOCK_LISTENER_LINES"
}

MOCK_LISTENER_LINES='udp UNCONN 0 0 0.0.0.0:10443 0.0.0.0:* users:(("xray",pid=101,fd=3))'
expect_success listener_owned_by_remnanode udp 10443
MOCK_LISTENER_LINES=$'udp UNCONN 0 0 0.0.0.0:10443 0.0.0.0:* users:(("xray",pid=101,fd=3))\nudp UNCONN 0 0 [::]:10443 [::]:* users:(("xray",pid=101,fd=4))'
expect_success listener_owned_by_remnanode udp 10443
MOCK_LISTENER_LINES='udp UNCONN 0 0 0.0.0.0:10443 0.0.0.0:* users:(("foreign",pid=202,fd=3),("xray",pid=101,fd=4))'
expect_failure listener_owned_by_remnanode udp 10443
MOCK_LISTENER_LINES=$'udp UNCONN 0 0 0.0.0.0:10443 0.0.0.0:* users:(("xray",pid=101,fd=3))\nudp UNCONN 0 0 [::]:10443 [::]:* users:(("foreign",pid=202,fd=4))'
expect_failure listener_owned_by_remnanode udp 10443
MOCK_LISTENER_LINES='udp UNCONN 0 0 0.0.0.0:10443 0.0.0.0:*'
expect_failure listener_owned_by_remnanode udp 10443
MOCK_LISTENER_LINES=''
expect_failure listener_owned_by_remnanode udp 10443
MOCK_CONTAINER_PIDS=''
MOCK_LISTENER_LINES='udp UNCONN 0 0 0.0.0.0:10443 0.0.0.0:* users:(("xray",pid=101,fd=3))'
expect_failure listener_owned_by_remnanode udp 10443

changed_tcp_collision() {
    (
        # These globals are consumed dynamically by sourced installer helpers.
        # shellcheck disable=SC2034
        HAD_MANAGED_INSTALL=1
        # shellcheck disable=SC2034
        PREVIOUS_NODE_PORT=2222
        # shellcheck disable=SC2034
        PREVIOUS_HY2_PORT=10443
        NODE_PORT=3333
        HY2_PORT=10443
        MOCK_CONTAINER_PIDS='101'
        MOCK_LISTENER_KEY='tcp:3333'
        MOCK_LISTENER_LINES='tcp LISTEN 0 128 0.0.0.0:3333 0.0.0.0:* users:(("node",pid=101,fd=3))'
        check_listener_collisions
    )
}
expect_failure changed_tcp_collision

changed_udp_collision() {
    (
        # These globals are consumed dynamically by sourced installer helpers.
        # shellcheck disable=SC2034
        HAD_MANAGED_INSTALL=1
        # shellcheck disable=SC2034
        PREVIOUS_NODE_PORT=2222
        # shellcheck disable=SC2034
        PREVIOUS_HY2_PORT=10443
        NODE_PORT=2222
        HY2_PORT=11443
        MOCK_CONTAINER_PIDS='101'
        MOCK_LISTENER_KEY='udp:11443'
        MOCK_LISTENER_LINES='udp UNCONN 0 0 0.0.0.0:11443 0.0.0.0:* users:(("xray",pid=101,fd=3))'
        check_listener_collisions
    )
}
expect_failure changed_udp_collision

printf 'function tests: PASS\n'
